services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      VIEW_DISTANCE: "30"
      VERSION: "1.20.1"
      TYPE: FORGE
      FORGE_VERSION: "47.3.0"
      WORLD: "/worlds/world"
      FORCE_WORLD_COPY: "true"
    volumes:
      - ./world:/worlds/world
      - ./data:/data
      - ./data/mc-mods/:/mods
   # entrypoint: ["./init.sh"]
